credentials:
  usernames:
    victor:
      email: victor@aberration.com
      name: Victor
      password: $2b$12$.ejUPQtRJR9cLgZd.e7fUeBpUFf5gXT/9RwXsZNCKhvWuT96wsywK
    glenn:
      email: glenn@aberration.com
      name: Glenn
      password: $2b$12$qc0s.S18jjQm7ZzUFmLBquo/omkAHOvm7BSCmGipyg8HBRaZZasLG
cookie:
  expiry_days: 30
  key: thecode_signature_key # Must be string
  name: thecode_cookie_name
preauthorized:
  emails:
