credentials:
  usernames:
    victor:
      email: victor@aberration.com
      name: Victor
      password: $2b$12$.ejUPQtRJR9cLgZd.e7fUeBpUFf5gXT/9RwXsZNCKhvWuT96wsywK
    glenn:
      email: glenn@aberration.com
      name: Glenn
      password: $2b$12$93UbGSUEsFyVkbqOfXpCVengRlGyNsHChzy0SXY5w44Lc8YOHuSVi
cookie:
  expiry_days: 30
  key: quesopa_signature_key # Must be string
  name: quesopa_cookie_name
preauthorized:
  emails:
